### ISSUE TITLE
Can’t archive App that uses a swift package with this xcframework

### ISSUE THREAD

**Issue by jimmyaat10** [SyncServerII/GSignIn#1]
Hello, 
thanks for this repo, it works like a charm.
I have a problem when adding xcframework inside a SPM Framework when archiving (works in the simulator).

Have you used the xcframework in a SPM Package?
Seems like a [Apple Bug](https://developer.apple.com/forums/thread/662247) but maybe you found a workaround.

My workaround for the moment is to embed the xcframework in the App Target directly and not in the SPM Package.

Thanks in advance

My SPM Package with the xcframework:

```
import PackageDescription

let package = Package(
    name: "Data",
    platforms: [.iOS(.v13)],
    products: [
        .library(
            name: "Data",
            targets: ["Data"]),
    ],
    dependencies: [
    ],
    targets: [
        .binaryTarget(
            name: "GSignIn",
            url: "https://github.com/SyncServerII/GSignIn/raw/main/XCFrameworks/GSignIn-5.0.2.xcframework.zip",
            checksum: "b2b468ca98bcbe7d771726cd2a1ea6f9bee785957af8c9f4c75aa10e5c337a52"
        ),
        .target(
            name: "Data",
            dependencies: [
                "GSignIn"
            ]
        ),
        .testTarget(
            name: "DataTests",
            dependencies: ["Data"]),
    ]
)```

**Comment by crspybits** [comment]
Hey-- Thanks for the report. I'm using it here:
https://github.com/SyncServerII/iOSGoogle.git

I definitely ran into a problem in archiving. I wrote up some notes here:
https://stackoverflow.com/questions/65469685/using-google-sign-in-for-ios-with-swift-package-manager/65469686#65469686

Not sure if that's enough to fix your issue. Happy to help a little later if not. Mid-work day for me. My app https://github.com/SyncServerII/Neebla (using https://github.com/SyncServerII/iOSGoogle.git) is archiving -- have been testing it on TestFlight.

**Comment by crspybits** [comment]
The secret sauce was here:
https://github.com/SyncServerII/iOSGoogle/blob/38dee7730ab27ae54e28437ebc48e688a842c111/Package.swift#L26

Let me know if you have more questions.

**Comment by jimmyaat10** [comment]
Thanks for the quick reply and for all the links / updates documenting your Package.swift and the errors you've solved during the integration process.

I'll give it a second try during the next week to see if your approach solves the `error: no such module 'GSignIn'` when archiving.
I made similar than you, maybe there's a missing subtility in my steps.

The steps:

- In the Package.swift of the SPM Local Package (aka Data) containing the GSignIn xcframework (like your iOSSignIn in the Neebla project). In my first attempt I didn't add the product library GSignIn, we'll see if this causes the problem.

```
let package = Package(
    name: "Data",
    platforms: [
        .iOS(.v13),
    ],
    products: [
        .library(
            name: "Data",
            targets: ["Data"]), 
         // In my first attempt I didn't add this      
        .library(
            name: "GSignIn",
            targets: ["GSignIn"]),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(
              name: "GSignIn",
              url: "https://github.com/SyncServerII/GSignIn/raw/main/XCFrameworks/GSignIn-5.0.2.xcframework.zip",
              checksum: "b2b468ca98bcbe7d771726cd2a1ea6f9bee785957af8c9f4c75aa10e5c337a52"
        ),
        .target(
            name: "Data",
            dependencies: [
                "GSignIn"
            ],
            resources: [
                .process("Resources/test.json")
            ]
        ),
        .testTarget(
            name: "DataTests",
            dependencies: ["Data"])
    ]
)
```

- I have added an Archive - Post Action script in the Data SPM Package scheme with:

```
full_frameworks_path="${ARCHIVE_PRODUCTS_PATH}/Applications/${FRAMEWORKS_FOLDER_PATH}"
echo "full_frameworks_path: ${full_frameworks_path}"
rm -rf "${full_frameworks_path}/GSignIn.framework"
```

In your example, you're doing a similar approach with a build phase script in the App Target with an Input file `$(BUILT_PRODUCTS_DIR)/$(PLUGINS_FOLDER_PATH)/GSignIn.framework`

and the script

```
# See https://forums.swift.org/t/swift-package-binary-framework-issue/41922/2
COUNTER=0
while [ $COUNTER -lt "${SCRIPT_INPUT_FILE_COUNT}" ]; do
    tmp="SCRIPT_INPUT_FILE_$COUNTER"
    FILE=${!tmp}

    echo "Removing $FILE"
    rm -rf "$FILE"
    let COUNTER=COUNTER+1
done
```

I'll try again with your approach to see if it's working.
